api_platform:
    resource: .
    type: api_platform
    prefix: /api
    mapping:
        # The list of paths with files or directories where the bundle will look for additional resource files.
        paths: [ ]
