controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

get_users:
    path: '/users/{id}'
    controller: App\Controller\UserController::Get
    methods: ['GET']