controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

get_trees:
    path: '/tree'
    controller: App\Controller\Tree\TreeGetCollectionController::Get
    methods: ['GET']

get_tree:
    path: '/tree/{id}'
    controller: App\Controller\Tree\TreeGetItemController::Get
    methods: ['GET']


put_tree:
    path: '/tree/{id}'
    controller: App\Controller\Tree\TreePutController::Put
    methods: ['PUT']

patch_tree:
    path: '/tree/{id}'
    controller: App\Controller\Tree\TreePatchController::Patch
    methods: ['PATCH']

delete_tree:
    path: '/tree/{id}'
    controller: App\Controller\Tree\TreeDeleteController::Delete
    methods: ['DELETE']